Revert "jabber: omemo: improoved 4.4, working on 4.5"
This reverts commit 26092086b62afd9bdef93f4756ae7558ec681e9a.

breaks compilation in MSVS 2010:

>src\jabber_omemo.cpp(1253): error C2059: syntax error : '{'
3>src\jabber_omemo.cpp(1253): error C2143: syntax error : missing ';' before '{'
3>src\jabber_omemo.cpp(1257): error C2143: syntax error : missing ';' before '}'